/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cajero.funciones;
import cajero.*;
import java.awt.Color;
import java.awt.Font;
/**
 *
 * @author ETHAN PIERCE
 */
public class ElegirCuenta extends javax.swing.JFrame {
    
    String user;
    String nCuentaU;
    boolean idioma;
    String tipoCuenta;
    /**
     * Creates new form ElegirCuenta
     * @param user
     * @param idioma
     */
    public ElegirCuenta(String user, boolean idioma) {
        initComponents();
        this.user = user;
        this.idioma = idioma;
        cambiarIdioma();
        jPanel1.setBackground(Color.getHSBColor(0.53f, 0.52f, 0.92f));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        eu = new javax.swing.JButton();
        dol = new javax.swing.JButton();
        bol = new javax.swing.JButton();
        elige = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setForeground(Color.WHITE);
        jButton1.setFont(new Font("Helvetica", Font.BOLD, 20));
        jButton1.setBackground(Color.getHSBColor(0.0f, 0.0f, 0.7f));

        eu.setText("Euro");
        eu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euActionPerformed(evt);
            }
        });
        eu.setForeground(Color.WHITE);
        eu.setFont(new Font("Helvetica", Font.BOLD, 20));
        eu.setBackground(Color.getHSBColor(0.0f, 0.0f, 0.7f));

        dol.setText("Dolar");
        dol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dolActionPerformed(evt);
            }
        });
        dol.setForeground(Color.WHITE);
        dol.setFont(new Font("Helvetica", Font.BOLD, 20));
        dol.setBackground(Color.getHSBColor(0.0f, 0.0f, 0.7f));

        bol.setText("Bs");
        bol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolActionPerformed(evt);
            }
        });
        bol.setForeground(Color.WHITE);
        bol.setFont(new Font("Helvetica", Font.BOLD, 20));
        bol.setBackground(Color.getHSBColor(0.0f, 0.0f, 0.7f));

        elige.setText("Elige tu cuenta");
        elige.setForeground(Color.WHITE);
        elige.setFont(new Font("Helvetica", Font.PLAIN, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bol, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .addComponent(dol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .addComponent(eu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(elige, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(503, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(elige, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bol, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(dol, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(eu, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 64, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(218, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolActionPerformed
        this.tipoCuenta = "Bolivianos";
        Cuentas c = new Cuentas();
        String nCuenta = c.getnCuenta(user,tipoCuenta);
        if(!nCuenta.equals("NA")){
        System.out.println(nCuenta);
        Sesion s = new Sesion(user,idioma,tipoCuenta);
        s.setVisible(true);
        dispose();
        }else{
            error.setText(idioma ? "No tiene una cuenta asociada a su CI." : "There is no account associated with your ID.");
        }
    }//GEN-LAST:event_bolActionPerformed

    private void dolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dolActionPerformed
        this.tipoCuenta = "Dolares";
        Cuentas c = new Cuentas();
        String nCuenta = c.getnCuenta(user,tipoCuenta);
        if(!nCuenta.equals("NA")){
        System.out.println(nCuenta);
        Sesion s = new Sesion(user,idioma,tipoCuenta);
        s.setVisible(true);
        dispose();
        }else{
            error.setText(idioma ? "No tiene una cuenta asociada a su CI." : "There is no account associated with your ID.");
        }
    }//GEN-LAST:event_dolActionPerformed

    private void euActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euActionPerformed
        this.tipoCuenta = "Euros";
        Cuentas c = new Cuentas();
        String nCuenta = c.getnCuenta(user,tipoCuenta);
        if(!nCuenta.equals("NA")){
        System.out.println(nCuenta);
        Sesion s = new Sesion(user,idioma,tipoCuenta);
        s.setVisible(true);
        dispose();
        }else{
            error.setText(idioma ? "No tiene una cuenta asociada a su CI." : "There is no account associated with your ID.");
        }
    }//GEN-LAST:event_euActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Principal p = new Principal();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
        public void cambiarIdioma(){
            Cuentas nombre = new Cuentas();
                elige.setText(idioma ? "Elige tu cuenta "+ nombre.getNombreCuenta(user) :"Choose your account "+ nombre.getNombreCuenta(user));
                
                String []tc = {"Bolivianos","Dolares","Euros"};
                for(int i = 0; i < tc.length; i++){
                        Cuentas c = new Cuentas();
                        String nCuenta = c.getnCuenta(user,tc[i]);
                        if(!nCuenta.equals("NA")){
                            switch(tc[i]){
                                case "Bolivianos":
                                    bol.setText("Saldo: "+c.getSaldo(nCuenta, tc[i])+" Bs");
                                    break;
                                 case "Dolares":
                                    dol.setText("Saldo: "+c.getSaldo(nCuenta, tc[i])+" $");
                                    break;
                                 case "Euros":
                                    eu.setText("Saldo: "+c.getSaldo(nCuenta, tc[i])+" E");
                                    break;
                            }
                        }else{
                            switch(tc[i]){
                                case "Bolivianos":
                                    bol.setText(idioma ? "No tiene una cuenta en Bs." : "There is no account associated with Bs.");
                                    break;
                                 case "Dolares":
                                    dol.setText(idioma ? "No tiene una cuenta en $." : "There is no account associated with $.");
                                    break;
                                 case "Euros":
                                    eu.setText(idioma ? "No tiene una cuenta en E." : "There is no account associated with E.");
                                    break;
//error.setText(idioma ? "No tiene una cuenta asociada a su CI." : "There is no account associated with your ID.");
                        }
                }
                
            }
        }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bol;
    private javax.swing.JButton dol;
    private javax.swing.JLabel elige;
    private javax.swing.JLabel error;
    private javax.swing.JButton eu;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
