/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cajero.funciones;
import cajero.*;
import cajero.Cuentas;
import java.awt.Color;
import java.awt.Font;
import javax.swing.SwingConstants;

/**
 *
 * @author ETHAN PIERCE
 */
public class Retirar extends javax.swing.JFrame {

    /**
     * Creates new form Retirar
     */
    String nCuenta;
    String user;
    boolean idioma;
    String tipoCuenta;
    int monto = 0;
    public Retirar(String nCuenta, String user, boolean idioma, String tipoCuenta) {
        initComponents();
        this.nCuenta = nCuenta;
        this.user = user;
        this.idioma = idioma;
        this.tipoCuenta = tipoCuenta;
        actualizarBalance();
        cambiarIdioma();
        bAccount.setText(nCuenta);
        jPanel1.setBackground(Color.getHSBColor(0.53f, 0.52f, 0.92f));
        b20.setForeground(Color.white);
        b20.setBackground(new Color(135, 206, 235));
        b20.setFont(new Font("Helvetica", Font.PLAIN, 25));
        b20.setHorizontalAlignment(SwingConstants.CENTER);
        b50.setForeground(Color.white);
        b50.setBackground(new Color(135, 206, 235));
        b50.setFont(new Font("Helvetica", Font.PLAIN, 25));
        b50.setHorizontalAlignment(SwingConstants.CENTER);
        b70.setForeground(Color.white);
        b70.setBackground(new Color(0, 0, 255));
        b70.setFont(new Font("Helvetica", Font.PLAIN, 25));
        b70.setHorizontalAlignment(SwingConstants.CENTER);
        b200.setForeground(Color.white);
        b200.setBackground(new Color(135, 206, 235));
        b200.setFont(new Font("Helvetica", Font.PLAIN, 25));
        b200.setHorizontalAlignment(SwingConstants.CENTER);
        bAccount.setHorizontalAlignment(SwingConstants.CENTER);
        bAccount.setFont(new Font("Arial", Font.PLAIN, 15));
        bAccount.setForeground(Color.white);
        bAmount.setHorizontalAlignment(SwingConstants.CENTER);
        bAmount.setFont(new Font("Arial", Font.BOLD, 20));
        bAmount.setForeground(Color.white);
        balance.setFont(new Font("Arial", Font.PLAIN, 15));
        balance.setForeground(Color.blue);
        account.setFont(new Font("Arial", Font.PLAIN, 15));
        account.setForeground(Color.blue);
        lMonto.setFont(new Font("Helvetica",Font.BOLD,30));
        lMonto.setForeground(Color.white);
        bAmount.setHorizontalAlignment(SwingConstants.LEFT);
        balance.setHorizontalAlignment(SwingConstants.LEFT);
        account.setHorizontalAlignment(SwingConstants.LEFT);
        bAccount.setHorizontalAlignment(SwingConstants.LEFT);
        tMonto.setFont((new Font("Helvetica",Font.PLAIN,25)));
        bVolver.setBackground(new Color(0, 0, 0, 0));
        bVolver.setForeground(Color.white);
        bVolver.setFont(new Font("Helvetica",Font.PLAIN,15));
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b200 = new javax.swing.JButton();
        b70 = new javax.swing.JButton();
        b50 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        bAccount = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        bAmount = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        bConfirmar = new javax.swing.JButton();
        bVolver = new javax.swing.JButton();
        tMonto = new javax.swing.JTextField();
        lMonto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b200.setText("$200");
        b200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b200ActionPerformed(evt);
            }
        });

        b70.setText("$ 70");
        b70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b70ActionPerformed(evt);
            }
        });

        b50.setText("$ 50");
        b50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b50ActionPerformed(evt);
            }
        });

        b20.setText("$ 20");
        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });

        account.setText("Nro Cuenta");

        balance.setText("Balance");

        bConfirmar.setText("Confirmar");
        bConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmarActionPerformed(evt);
            }
        });

        bVolver.setText("Volver");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });

        tMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMontoActionPerformed(evt);
            }
        });

        lMonto.setText("Retiro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(account, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b70, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(b200, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(b50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(tMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bVolver, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bConfirmar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bVolver)
                        .addGap(22, 22, 22)
                        .addComponent(tMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b50, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b70, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b200, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(bAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(account, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(bConfirmar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmarActionPerformed
        int monto = Integer.parseInt(tMonto.getText());
        Cuentas cuenta = new Cuentas();
        if(Integer.parseInt(cuenta.getSaldo(nCuenta, this.tipoCuenta)) >= monto){
            cuenta.retirar(monto, this.nCuenta);
            Transaccion t = new Transaccion();
            t.crearTransaccion(nCuenta,"Retiro",monto,tipoCuenta,nCuenta);
        }else{
            tMonto.setText("MONTO INSUFICIENTE");
        }
        actualizarBalance();
        
    }//GEN-LAST:event_bConfirmarActionPerformed

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        Sesion s = new Sesion(user, idioma, tipoCuenta);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bVolverActionPerformed

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
        monto = monto+20;
        tMonto.setText(String.valueOf(monto));
    }//GEN-LAST:event_b20ActionPerformed

    private void tMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMontoActionPerformed
        
    }//GEN-LAST:event_tMontoActionPerformed

    private void b50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b50ActionPerformed
        monto = monto+50;
        tMonto.setText(String.valueOf(monto));
    }//GEN-LAST:event_b50ActionPerformed

    private void b70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b70ActionPerformed
        monto = monto+70;
        tMonto.setText(String.valueOf(monto));
    }//GEN-LAST:event_b70ActionPerformed

    private void b200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b200ActionPerformed
        monto = monto+200;
        tMonto.setText(String.valueOf(monto));
    }//GEN-LAST:event_b200ActionPerformed

    /**
     * @param args the command line arguments
     */
       public void cambiarIdioma(){
       if(idioma == false)
       {
           lMonto.setText("Withdraw");
           bConfirmar.setText("Confirm");
           bVolver.setText("Home");
           account.setText("Account Number.");
       }
       
   }
       public void actualizarBalance(){
           Cuentas cuenta = new Cuentas();
           bAmount.setText("$"+cuenta.getSaldo(nCuenta, this.tipoCuenta));
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account;
    private javax.swing.JButton b20;
    private javax.swing.JButton b200;
    private javax.swing.JButton b50;
    private javax.swing.JButton b70;
    private javax.swing.JLabel bAccount;
    private javax.swing.JLabel bAmount;
    private javax.swing.JButton bConfirmar;
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel balance;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lMonto;
    private javax.swing.JTextField tMonto;
    // End of variables declaration//GEN-END:variables
}
