/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cajero.funciones;

import cajero.Cuentas;
import java.awt.Color;
import java.awt.Font;
import javax.swing.SwingConstants;

/**
 *
 * @author ETHAN PIERCE
 */
public class Saldo extends javax.swing.JFrame {

    /**
     * Creates new form Saldo
     */
    String nCuenta;
    String tipoCuenta;
    String user;
    boolean idioma;
    public Saldo(String nCuenta, String user, boolean idioma, String tipoCuenta) {
        initComponents();
        this.nCuenta = nCuenta;
        this.tipoCuenta = tipoCuenta;
        this.user = user;
        this.idioma = idioma;
        cambiarIdioma();
        mostrarSaldo();
        jPanel1.setBackground(Color.getHSBColor(0.53f, 0.52f, 0.92f));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lMonto = new javax.swing.JLabel();
        bVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lMonto.setForeground(Color.WHITE);
        lMonto.setFont(new Font("Helvetica", Font.BOLD, 30));

        bVolver.setText("Volver");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });
        bVolver.setForeground(Color.WHITE);
        bVolver.setFont(new Font("Helvetica", Font.BOLD, 20));

        jLabel1.setText("Saldo Disponible");
        jLabel1.setForeground(Color.WHITE);
        jLabel1.setFont(new Font("Helvetica", Font.BOLD, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(lMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap(519, Short.MAX_VALUE)
                            .addComponent(bVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(lMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                    .addComponent(bVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        Sesion s = new Sesion(user, idioma, tipoCuenta);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bVolverActionPerformed
    public void mostrarSaldo(){
        Cuentas cuenta = new Cuentas();
        lMonto.setText(cuenta.getSaldo(nCuenta, tipoCuenta));
    }
    /**
     * @param args the command line arguments
     */
    
   public void cambiarIdioma(){
       if(idioma == false)
       {
           lMonto.setText("Balance");
           bVolver.setText("Go Back");
           jLabel1.setText("Balance Available");
           jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
           lMonto.setHorizontalAlignment(SwingConstants.CENTER);
           lMonto.setForeground(Color.gray);
           jLabel1.setFont(new Font("Times New Roman", Font.PLAIN, 17));
           lMonto.setFont(new Font("Times New Roman", Font.PLAIN, 17));
       }
       jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
           lMonto.setHorizontalAlignment(SwingConstants.CENTER);
           lMonto.setForeground(Color.gray);
           jLabel1.setFont(new Font("Times New Roman", Font.PLAIN, 17));
           lMonto.setFont(new Font("Times New Roman", Font.PLAIN, 17));
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lMonto;
    // End of variables declaration//GEN-END:variables
}
