package cajero;
import cajero.funciones.Sesion;
import cajero.funciones.ElegirCuenta;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.util.Arrays;
import java.awt.Font;
import java.awt.Image;
import javax.swing.Icon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ETHAN PIERCE
 */
public class Principal extends javax.swing.JFrame {
    String vNombre;
    String vAp;
    String vAm;
    int vCi;
    int vDia;
    int vMes;
    int vAnio;
    String vUsuario;
    String vPassword;
    String tipoCuenta; 
    //true ES false EN
    boolean idioma = true;
    
    /**
     * Creates new form Principal1
     */
    public Principal() {
        
        initComponents();
        //Ya me dio paja hacer los estilos en un metodo
        mostrarBanderas();
        Registrarse.setBackground(Color.getHSBColor(0.53f, 0.52f, 0.92f));
        Sesion.setBackground(Color.getHSBColor(0.53f, 0.52f, 0.92f));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        Sesion = new javax.swing.JPanel();
        lUsuario = new javax.swing.JLabel();
        lPin = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        bIniciar = new javax.swing.JButton();
        errorSesion = new javax.swing.JLabel();
        english = new javax.swing.JLabel();
        spanish = new javax.swing.JLabel();
        Registrarse = new javax.swing.JPanel();
        lNombre = new javax.swing.JLabel();
        lAp = new javax.swing.JLabel();
        lAm = new javax.swing.JLabel();
        lCi = new javax.swing.JLabel();
        lFecha = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        tAp = new javax.swing.JTextField();
        tAm = new javax.swing.JTextField();
        tCi = new javax.swing.JTextField();
        tDia = new javax.swing.JTextField();
        tMes = new javax.swing.JTextField();
        tAnio = new javax.swing.JTextField();
        bCrear = new javax.swing.JButton();
        english1 = new javax.swing.JLabel();
        spanish1 = new javax.swing.JLabel();
        bolivianos = new javax.swing.JRadioButton();
        dolares = new javax.swing.JRadioButton();
        euros = new javax.swing.JRadioButton();
        errorRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        lUsuario.setText("Usuario");
        lUsuario.setForeground(Color.WHITE);
        lUsuario.setFont(new Font("Helvetica", Font.PLAIN, 20));

        lPin.setText("PIN");
        lPin.setForeground(Color.WHITE);
        lPin.setFont(new Font("Helvetica", Font.PLAIN, 20));

        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        bIniciar.setText("Iniciar");
        bIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIniciarActionPerformed(evt);
            }
        });
        bIniciar.setForeground(Color.WHITE);
        bIniciar.setFont(new Font("Helvetica", Font.BOLD, 20));
        bIniciar.setBackground(Color.getHSBColor(0.0f, 0.0f, 0.7f));

        errorSesion.setText("INGRESE CREDENCIALES");
        errorSesion.setForeground(Color.WHITE);
        errorSesion.setFont(new Font("Helvetica", Font.PLAIN, 25));

        english.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                englishMouseClicked(evt);
            }
        });

        spanish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spanishMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SesionLayout = new javax.swing.GroupLayout(Sesion);
        Sesion.setLayout(SesionLayout);
        SesionLayout.setHorizontalGroup(
            SesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(SesionLayout.createSequentialGroup()
                .addGroup(SesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SesionLayout.createSequentialGroup()
                        .addGroup(SesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SesionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(english, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spanish, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SesionLayout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(SesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SesionLayout.createSequentialGroup()
                                        .addComponent(lPin, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                        .addGap(43, 43, 43))
                                    .addGroup(SesionLayout.createSequentialGroup()
                                        .addComponent(lUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(9, 9, 9)))))
                        .addGroup(SesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))))
                .addGap(328, 328, 328))
        );
        SesionLayout.setVerticalGroup(
            SesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(SesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(SesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(bIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(SesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(english, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spanish, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(424, 424, 424))
        );

        jTabbedPane2.addTab("Iniciar Sesion", Sesion);

        lNombre.setText("Nombre(s)");
        lNombre.setForeground(Color.WHITE);
        lNombre.setFont(new Font("Helvetica", Font.PLAIN, 20));

        lAp.setText("Apellido Paterno");
        lAp.setForeground(Color.WHITE);
        lAp.setFont(new Font("Helvetica", Font.PLAIN, 20));

        lAm.setText("Apellido Materno");
        lAm.setForeground(Color.WHITE);
        lAm.setFont(new Font("Helvetica", Font.PLAIN, 20));

        lCi.setText("Cedula de Identidad");
        lCi.setForeground(Color.WHITE);
        lCi.setFont(new Font("Helvetica", Font.PLAIN, 20));

        lFecha.setText("Fecha de nacimiento");
        lFecha.setForeground(Color.WHITE);
        lFecha.setFont(new Font("Helvetica", Font.PLAIN, 20));

        tNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreActionPerformed(evt);
            }
        });

        tAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tApActionPerformed(evt);
            }
        });

        tAm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAmActionPerformed(evt);
            }
        });

        tCi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCiActionPerformed(evt);
            }
        });

        tDia.setText("00");
        tDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDiaActionPerformed(evt);
            }
        });

        tMes.setText("00");
        tMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMesActionPerformed(evt);
            }
        });

        tAnio.setText("0000");
        tAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAnioActionPerformed(evt);
            }
        });

        bCrear.setText("Crear Cuenta");
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });
        bCrear.setForeground(Color.WHITE);
        bCrear.setFont(new Font("Helvetica", Font.BOLD, 20));
        bCrear.setBackground(Color.getHSBColor(0.0f, 0.0f, 0.7f));

        english1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                english1MouseClicked(evt);
            }
        });

        spanish1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spanish1MouseClicked(evt);
            }
        });

        bolivianos.setText("Bolivianos (Bs.)");
        bolivianos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolivianosActionPerformed(evt);
            }
        });
        bolivianos.setForeground(Color.WHITE);
        bolivianos.setFont(new Font("Helvetica", Font.PLAIN, 20));

        dolares.setText("Dolares ($)");
        dolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dolaresActionPerformed(evt);
            }
        });
        dolares.setForeground(Color.WHITE);
        dolares.setFont(new Font("Helvetica", Font.PLAIN, 20));

        euros.setText("Euros (€)");
        euros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eurosActionPerformed(evt);
            }
        });
        euros.setForeground(Color.WHITE);
        euros.setFont(new Font("Helvetica", Font.PLAIN, 20));

        javax.swing.GroupLayout RegistrarseLayout = new javax.swing.GroupLayout(Registrarse);
        Registrarse.setLayout(RegistrarseLayout);
        RegistrarseLayout.setHorizontalGroup(
            RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrarseLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(errorRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(RegistrarseLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrarseLayout.createSequentialGroup()
                        .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lCi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistrarseLayout.createSequentialGroup()
                                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tCi, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                                    .addGroup(RegistrarseLayout.createSequentialGroup()
                                        .addComponent(tDia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tMes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(111, 111, 111))
                            .addGroup(RegistrarseLayout.createSequentialGroup()
                                .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(english1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spanish1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))))
                    .addGroup(RegistrarseLayout.createSequentialGroup()
                        .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lAp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lAm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistrarseLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(tAm))
                            .addGroup(RegistrarseLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tAp, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(285, 285, 285))
                    .addGroup(RegistrarseLayout.createSequentialGroup()
                        .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bCrear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bolivianos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dolares, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(euros, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        RegistrarseLayout.setVerticalGroup(
            RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrarseLayout.createSequentialGroup()
                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrarseLayout.createSequentialGroup()
                        .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistrarseLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(english1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lAp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegistrarseLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(tAp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lAm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegistrarseLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(tAm))))
                    .addComponent(spanish1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bolivianos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(euros, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dolares, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(bCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(errorRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Registrarse", Registrarse);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAnioActionPerformed

    private void tMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMesActionPerformed

    private void tDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDiaActionPerformed

    private void tCiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCiActionPerformed

    private void tAmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAmActionPerformed

    private void tApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tApActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tApActionPerformed

    private void tNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreActionPerformed

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
    
// TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void english1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_english1MouseClicked
        lUsuario.setText("User");
        lNombre.setText("Name(s)");
        lAp.setText("Last name");
        lAm.setText("Maternal Last Name");
        lFecha.setText("Date of Birth");
        lCi.setText("Identity Card");
        bIniciar.setText("Sign In");
        bCrear.setText("Sign On");
        jTabbedPane2.setTitleAt(0, "Sign In");
        jTabbedPane2.setTitleAt(1, "Sign On");
        idioma = false;
// TODO add your handling code here:
    }//GEN-LAST:event_english1MouseClicked

    private void spanish1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spanish1MouseClicked
        lUsuario.setText("Usuario");
        lNombre.setText("Nombre(s)");
        lAp.setText("Apellido Paterno");
        lAm.setText("Apellido Materno");
        lFecha.setText("Fecha De Nacimiento");
        lCi.setText("Cedula De Identidad");
        bIniciar.setText("Iniciar Sesion");
        bCrear.setText("Registrarse");
        jTabbedPane2.setTitleAt(0, "Iniciar Sesion");
        jTabbedPane2.setTitleAt(1, "Registrarse");
        idioma = true;
// TODO add your handling code here:
    }//GEN-LAST:event_spanish1MouseClicked

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        vNombre = tNombre.getText();
        vAp = tAp.getText();
        vAm = tAm.getText();
        vCi = Integer.parseInt(tCi.getText());
        vDia = Integer.parseInt(tDia.getText());
        vMes = Integer.parseInt(tMes.getText());
        vAnio = Integer.parseInt(tAnio.getText());
        if (bolivianos.isSelected()) {
            tipoCuenta = "Bolivianos";
        } else if (dolares.isSelected()) {
            tipoCuenta = "Dolares";
        } else if (euros .isSelected()) {
            tipoCuenta = "Euros";
        }else{
            tipoCuenta = "Bolivianos";
        }
        Cuentas cuenta = new Cuentas(vNombre, vAp, vAm, vCi, vDia,vMes,vAnio,tipoCuenta);
        if(cuenta.leerCuentasCrear()){
            errorRegistro.setText(idioma ? "YA EXISTE UNA CUENTA ASI" : "Account Already Exists");

            
        }else{
            Validar v = new Validar(vNombre, vAp, vAm, vCi, vDia,vMes,vAnio,tipoCuenta, idioma);
            if(!v.crearCuentaDistinta(vCi, tipoCuenta)){
            v.setVisible(true);
            this.dispose();
            }else{
                 errorRegistro.setText(idioma ? "Se creo una cuenta con el mismo Pin y Usuario del CI ingresado." : "A account was created with the same PIN and User as the entered ID.");
            }
            
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_bCrearActionPerformed

    private void bolivianosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolivianosActionPerformed
        euros.setSelected(false);
        dolares.setSelected(false);
// TODO add your handling code here:
    }//GEN-LAST:event_bolivianosActionPerformed

    private void dolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dolaresActionPerformed
        bolivianos.setSelected(false);
        euros.setSelected(false);
    }//GEN-LAST:event_dolaresActionPerformed

    private void eurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eurosActionPerformed
        bolivianos.setSelected(false);
        dolares.setSelected(false);
    }//GEN-LAST:event_eurosActionPerformed

    private void spanishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spanishMouseClicked
        errorSesion.setText("INGRESE CREDENCIALES");
        lUsuario.setText("Usuario");
        lNombre.setText("Nombre(s)");
        lAp.setText("Apellido Paterno");
        lAm.setText("Apellido Materno");
        lFecha.setText("Fecha De Nacimiento");
        lCi.setText("Cedula De Identidad");
        bIniciar.setText("Iniciar Sesion");
        bCrear.setText("Registrarse");
        jTabbedPane2.setTitleAt(0, "Iniciar Sesion");
        jTabbedPane2.setTitleAt(1, "Registrarse");
        idioma = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_spanishMouseClicked

    private void englishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_englishMouseClicked
        errorSesion.setText("ENTER CREDENTIALS");
        lUsuario.setText("User");
        lNombre.setText("Name(s)");
        lAp.setText("Last name");
        lAm.setText("Maternal Last Name");
        lFecha.setText("Date of Birth");
        lCi.setText("Identity Card");
        bIniciar.setText("Sign In");
        bCrear.setText("Sign On");
        jTabbedPane2.setTitleAt(0, "Sign In");
        jTabbedPane2.setTitleAt(1, "Sign On");
        idioma = false;
    }//GEN-LAST:event_englishMouseClicked

    private void bIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarActionPerformed
        String userMandado = usuario.getText();
        int pin = Integer.parseInt(password.getText());
        Cuentas cInicio = new Cuentas();
        if(cInicio.iniciarSesion(userMandado, pin)){
            ElegirCuenta e = new ElegirCuenta(userMandado, idioma);
            e.setVisible(true);
            this.dispose();
        }else{
            errorSesion.setText(idioma ? "Credenciales Erroneas." : "Wrong Credentials");
        }

    }//GEN-LAST:event_bIniciarActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void mostrarBanderas(){
        Icon iconoSE = new ImageIcon(new ImageIcon(getClass().getResource("/recursos/english.jpg")).getImage().getScaledInstance(english.getWidth(), english.getHeight(),Image.SCALE_SMOOTH));
        this.english.setIcon(iconoSE);
        Icon iconoSS = new ImageIcon(new ImageIcon(getClass().getResource("/recursos/spanish.jpg")).getImage().getScaledInstance(english.getWidth(), english.getHeight(),Image.SCALE_SMOOTH));
        this.spanish.setIcon(iconoSS);
        Icon iconoRE = new ImageIcon(new ImageIcon(getClass().getResource("/recursos/english.jpg")).getImage().getScaledInstance(english.getWidth(), english.getHeight(),Image.SCALE_SMOOTH));
        this.english1.setIcon(iconoRE);
        Icon iconoRS = new ImageIcon(new ImageIcon(getClass().getResource("/recursos/spanish.jpg")).getImage().getScaledInstance(english.getWidth(), english.getHeight(),Image.SCALE_SMOOTH));
        this.spanish1.setIcon(iconoRS);
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Registrarse;
    private javax.swing.JPanel Sesion;
    private javax.swing.JButton bCrear;
    private javax.swing.JButton bIniciar;
    private javax.swing.JRadioButton bolivianos;
    private javax.swing.JRadioButton dolares;
    private javax.swing.JLabel english;
    private javax.swing.JLabel english1;
    private javax.swing.JLabel errorRegistro;
    private javax.swing.JLabel errorSesion;
    private javax.swing.JRadioButton euros;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lAm;
    private javax.swing.JLabel lAp;
    private javax.swing.JLabel lCi;
    private javax.swing.JLabel lFecha;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lPin;
    private javax.swing.JLabel lUsuario;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel spanish;
    private javax.swing.JLabel spanish1;
    private javax.swing.JTextField tAm;
    private javax.swing.JTextField tAnio;
    private javax.swing.JTextField tAp;
    private javax.swing.JTextField tCi;
    private javax.swing.JTextField tDia;
    private javax.swing.JTextField tMes;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
