/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cajero;

import java.awt.Color;
import java.awt.Font;
import javax.swing.SwingUtilities;

/**
 *
 * @author ETHAN PIERCE
 */
public class Validar extends javax.swing.JFrame {
    String usuario;
    int password;
    String nombre, Ap,  Am, tipoCuenta;
    int ci, dia, mes, anio;
    boolean idioma;
    int tiempoRestante = 5;
     
    /**
     * Creates new form Validar
     */
    public Validar(){
        initComponents();
    }
    
    public Validar(String nombre, String Ap, String Am, int ci, int dia, int mes, int anio, String tipoCuenta, boolean idioma) {
        initComponents();
        this.nombre = nombre;
        this.Ap = Ap;
        this.Am = Am;
        this.tipoCuenta = tipoCuenta;
        this.ci = ci;
        this.dia = dia;
        this.mes = mes;
        this.anio = anio;
        this.idioma = idioma;
        cambiarIdioma();
        jPanel1.setBackground(Color.getHSBColor(0.53f, 0.52f, 0.92f));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        existe = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tPassword = new javax.swing.JPasswordField();
        tUsuario = new javax.swing.JTextField();
        lPin = new javax.swing.JLabel();
        lUser = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        //jLabel3.setText("FALLO AL CREAR LA CUENTA \n REVISE CREDENCIALES");

        jLabel4.setText("INGRESE UN USUARIO Y PIN");
        //jLabel3.setText("FALLO AL CREAR LA CUENTA \n REVISE CREDENCIALES");

        tUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUsuarioActionPerformed(evt);
            }
        });

        lPin.setText("PIN");
        lPin.setForeground(Color.WHITE);
        lPin.setFont(new Font("Helvetica", Font.PLAIN, 20));

        lUser.setText("Usuario");
        lUser.setForeground(Color.WHITE);
        lUser.setFont(new Font("Helvetica", Font.PLAIN, 20));

        jButton1.setText("Crear cuenta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lPin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lUser, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(235, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(173, 173, 173)
                    .addComponent(existe, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addGap(173, 173, 173)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lUser, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lPin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(355, 355, 355)
                    .addComponent(existe, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                 usuario = tUsuario.getText();
        password = Integer.parseInt(tPassword.getText());
        Validacion validacion = new Validacion(usuario, password);
        if (validacion.existe()) {
            existe.setText("EL USUARIO EXISTE, INGRESE OTRO");
        } else {
            System.out.println("LLEGUE A CREAR CUENTA");
            Cuentas cuenta = new Cuentas(nombre, Ap, Am, ci, dia, mes, anio, tipoCuenta, usuario, password);
            cuenta.crearCuenta();

            existe.setText(idioma ? "Cuenta creada en " + tiempoRestante + " segundos, volverá al inicio" : "Account created in " + tiempoRestante + " seconds, back to home.");

            tUsuario.setVisible(false);
            tPassword.setVisible(false);
            jButton1.setVisible(false);
            lUser.setVisible(false);
            lPin.setVisible(false);
            jLabel4.setVisible(false);

            new Thread(() -> {
                try {
                    while (tiempoRestante > 0) {
                        Thread.sleep(1000);
                        tiempoRestante--;
                        SwingUtilities.invokeLater(() -> {
                            if (idioma) {
                                existe.setText("Cuenta creada en " + tiempoRestante + " segundos, volverá al inicio.");
                            } else {
                                existe.setText("Account created in " + tiempoRestante + " seconds, back to home.");
                            }
                        });
                    }
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                SwingUtilities.invokeLater(() -> {
                    Principal p = new Principal();
                    p.setVisible(true);
                    dispose();
                });
            }).start();
        
}
        


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    public boolean crearCuentaDistinta(int ci, String tipocuenta){
            Cuentas cue = new Cuentas(nombre, Ap, Am, ci, dia, mes, anio, tipocuenta);
            if(cue.crearCuentaExiste(ci, tipocuenta)){
                return true;
            }
            return false;
    }
    
     public void cambiarIdioma(){
            if(!idioma){
                jLabel4.setText("Input A Username & PIN");
                lUser.setText("Username");
                jButton1.setText("Sign On");
            }
        }
     
         public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new Validar().setVisible(true));
    }
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
      

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Validar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Validar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Validar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Validar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Validar().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel existe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lPin;
    private javax.swing.JLabel lUser;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUsuario;
    // End of variables declaration//GEN-END:variables
}
